### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by thezeeck** [HCL-TECH-SOFTWARE/dxsync#5]
Hi, i have an error when i try to do the installation.

1044 verbose stack Error: ENOENT: no such file or directory, access 'C:\DXSyncCLI-1.0.3\node_modules\ansi-regex'
1045 verbose cwd C:\DXSyncCLI-1.0.3
1046 verbose Windows_NT 10.0.17763
1047 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "--production" "install"
1048 verbose node v11.8.0
1049 verbose npm  v6.5.0
1050 error path C:\DXSyncCLI-1.0.3\node_modules\ansi-regex
1051 error code ENOENT
1052 error errno -4058
1053 error syscall access
1054 error enoent ENOENT: no such file or directory, access 'C:\DXSyncCLI-1.0.3\node_modules\ansi-regex'
1055 error enoent This is related to npm not being able to find a file.
1056 verbose exit [ -4058, true ]

Node version: 11.8.0
NPM version: 6.5.0
OS: Windows

**Comment by ThomasHurek** [comment]
Dear @thezeeck, it seems you are using an older version of node. From our doc: You must have Node 12 to install Digital Experience File Sync. 
Could you try with node 12 and let us know if that does not fix it?

**Comment by ThomasHurek** [comment]
Have not heard anything on this ticket so will close for now. Please reopen as needed.
